export const RULER_WALLET_PAGE_INITIAL_WIDTH = 375;
export const RULER_WALLET_PAGE_INITIAL_HEIGHT = 667;

export const RULER_WALLET_IMAGE_INITIAL_WIDTH = 375;
export const RULER_WALLET_IMAGE_ORIGIN_WIDTH = 430;
export const RULER_WALLET_IMAGE_INITIAL_HEIGHT = 303;
export const RULER_WALLET_IMAGE_INITIAL_POSITION_RIGHT = -55;
