export const BUTTON_BLACK_COLOR_TYPE_TEXT_COLOR = '#FFF';
export const BUTTON_BLACK_COLOR_TYPE_BACKGROUND_COLOR = '#303331'; // '#181c19';
export const BUTTON_BLACK_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#000000';
export const BUTTON_BLACK_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#babbba';
export const BUTTON_GREEN_COLOR_TYPE_DISABLED_BACKGROUND_COLOR_DARK_MODE = '#303331';
export const BUTTON_GREEN_COLOR_TYPE_TEXT_COLOR = '#FFF';
export const BUTTON_GREEN_COLOR_TYPE_BACKGROUND_COLOR = '#00b559';
export const BUTTON_GREEN_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#00ab55';
export const BUTTON_GREEN_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#caf1dd';

export const BUTTON_LIGHT_GREEN_COLOR_TYPE_TEXT_COLOR = '#00b559';
export const BUTTON_LIGHT_GREEN_COLOR_TYPE_BACKGROUND_COLOR = '#caf1dd';
export const BUTTON_LIGHT_GREEN_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#b6ecd0';
export const BUTTON_LIGHT_GREEN_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#f2fcf7';
