export const DEFAULT_ICON_SIZE = 30;
export const ICON_BLACK_COLOR_TYPE_PRIMARY_COLOR = '#181C19';
export const ICON_BLACK_COLOR_TYPE_PRIMARY_COLOR_DARK = '#fff';
export const ICON_BLACK_COLOR_TYPE_SECONDARY_COLOR = '#F8CA06';
export const ICON_GREEN_COLOR_TYPE_COLOR = '#00b559';
export const ICON_WHITE_COLOR_TYPE_COLOR = '#FFF';
