export const CREATE_WALLET_PAGE_INITIAL_WIDTH = 375;
export const CREATE_WALLET_PAGE_INITIAL_HEIGHT = 667;

export const CREATE_WALLET_IMAGE_INITIAL_WIDTH = 380;
export const CREATE_WALLET_IMAGE_INITIAL_HEIGHT = 288;
export const CREATE_WALLET_IMAGE_INITIAL_POSITION_RIGHT = 9.7;
