export const WELCOME_PAGE_INITIAL_WIDTH = 375;
export const WELCOME_PAGE_INITIAL_HEIGHT = 667;

export const WELCOME_PAGE_BACKGROUND_INITIAL_WIDTH = 555;
export const WELCOME_PAGE_BACKGROUND_INITIAL_HEIGHT = 907;
export const WELCOME_PAGE_BACKGROUND_INITIAL_POSITION_TOP = -671.7;
export const WELCOME_PAGE_BACKGROUND_INITIAL_POSITION_RIGHT = -187;

export const WELCOME_PAGE_CONTENT_INITIAL_WIDTH = 265;
export const WELCOME_PAGE_CONTENT_INITIAL_HEIGHT = 399;
export const WELCOME_PAGE_CONTENT_MAX_WIDTH = WELCOME_PAGE_CONTENT_INITIAL_WIDTH;
export const WELCOME_PAGE_CONTENT_INITIAL_PADDING_BOTTOM = 30;
