export const Dialog_BLACK_COLOR_TYPE_TEXT_COLOR = '#FFF';
export const Dialog_BLACK_COLOR_TYPE_BACKGROUND_COLOR = '#181c19';
export const Dialog_BLACK_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#000000';
export const Dialog_BLACK_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#babbba';

export const Dialog_GREEN_COLOR_TYPE_TEXT_COLOR = '#FFF';
export const Dialog_GREEN_COLOR_TYPE_BACKGROUND_COLOR = '#00b559';
export const Dialog_GREEN_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#00ab55';
export const Dialog_GREEN_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#caf1dd';

export const Dialog_LIGHT_GREEN_COLOR_TYPE_TEXT_COLOR = '#00b559';
export const Dialog_LIGHT_GREEN_COLOR_TYPE_BACKGROUND_COLOR = '#caf1dd';
export const Dialog_LIGHT_GREEN_COLOR_TYPE_HOVERED_BACKGROUND_COLOR = '#b6ecd0';
export const Dialog_LIGHT_GREEN_COLOR_TYPE_DISABLED_BACKGROUND_COLOR = '#f2fcf7';
