export const LINK_BLACK_COLOR_TYPE_TEXT_COLOR = '#181c19';
export const LINK_BLACK_COLOR_TYPE_HOVERED_TEXT_COLOR = '#303732';
export const LINK_BLACK_COLOR_TYPE_PRESSED_TEXT_COLOR = '#000100';
export const LINK_GREEN_COLOR_TYPE_TEXT_COLOR = '#009c4c';
export const LINK_GREEN_COLOR_TYPE_HOVERED_TEXT_COLOR = '#00cf65';
export const LINK_GREEN_COLOR_TYPE_PRESSED_TEXT_COLOR = '#008240';
